// Auto-generated by scripts/build-photo-manifest.ts. Do not edit by hand.
// Re-run: npm run photos:manifest

export type Photo = {
  src: string;
  width: number;
  height: number;
  alt: string;
  blurDataURL: string;
};

export const photos: Photo[] = [];
