import fs from "node:fs/promises";
import path from "node:path";
import { getPlaiceholder } from "plaiceholder";

const PHOTOS_DIR = path.join(process.cwd(), "public", "photos");
const MANIFEST_PATH = path.join(process.cwd(), "content", "photos.ts");
const IMAGE_EXTS = new Set([".jpg", ".jpeg", ".png", ".webp", ".avif"]);

type Photo = {
  src: string;
  width: number;
  height: number;
  alt: string;
  blurDataURL: string;
};

function titleFromFilename(filename: string): string {
  return filename
    .replace(/\.[^.]+$/, "")
    .replace(/[-_]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

async function main() {
  await fs.mkdir(PHOTOS_DIR, { recursive: true });
  await fs.mkdir(path.dirname(MANIFEST_PATH), { recursive: true });

  const entries = await fs.readdir(PHOTOS_DIR);
  const files = entries
    .filter((e) => IMAGE_EXTS.has(path.extname(e).toLowerCase()))
    .sort();

  const photos: Photo[] = [];
  for (const file of files) {
    const buffer = await fs.readFile(path.join(PHOTOS_DIR, file));
    const { base64, metadata } = await getPlaiceholder(buffer, { size: 10 });
    if (!metadata.width || !metadata.height) {
      console.warn(`Skipping ${file}: missing dimensions`);
      continue;
    }
    photos.push({
      src: `/photos/${file}`,
      width: metadata.width,
      height: metadata.height,
      alt: titleFromFilename(file),
      blurDataURL: base64,
    });
  }

  const output = `// Auto-generated by scripts/build-photo-manifest.ts. Do not edit by hand.
// Re-run: npm run photos:manifest

export type Photo = {
  src: string;
  width: number;
  height: number;
  alt: string;
  blurDataURL: string;
};

export const photos: Photo[] = ${JSON.stringify(photos, null, 2)};
`;

  await fs.writeFile(MANIFEST_PATH, output, "utf8");
  console.log(`Wrote ${photos.length} photo${photos.length === 1 ? "" : "s"} → ${path.relative(process.cwd(), MANIFEST_PATH)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
